name: "Basic checks"
on: [push, pull_request]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.3'
    - uses: actions/checkout@v1
    - name: "make ci"
      run: make ci

