name: "Test building docker image"
on: [push, pull_request]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test building the Docker image
        run: make docker

